name: CI

on:
  push:
    branches: [ part1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.
          
      - name: Build part 1
        run: cd part1 && go build
      
      - name: Test part 1
        run: cd part1 && go test -v -cover uniq/unique

      - name: Build part 2
        run: cd part2 && go build
      
      - name: Test part 2
        run: cd part2 && go test -v -cover calc/calculator
